In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("/Users/camillascandola/Desktop/tokyo_buildings.gpkg")

df = pd.read_sql("SELECT * FROM buildings;", conn)

In [2]:
df.shape

(2736007, 25)

In [3]:
df.head()

,fid,geom,gml_id,建物ID,大字・町コード,町・丁目コード,13_区市町村コード_大字・町コード_町・丁目コード,規模,浸水ランク,value,...,buildingRoofEdgeArea,buildingRoofEdgeArea_uom,districtsAndZonesType,prefecture,city,surveyYear,key,codeValue,name,tokyo_ward
0,1,b'GP\x00\x05\x0c\x1a\x00\x00\x0fYDA\xcava@\xbd...,BLD_fc50c7d9-76ac-4576-bfbd-f37c74410928,13111-bldg-524,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.8400000000000001, 3.3100000000000001, 13.9...",...,40.43768,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None
1,2,"b'GP\x00\x05\x0c\x1a\x00\x00""ht&\xa0va@\\\xc9\...",BLD_2e11a57e-c315-4351-8cca-22649d9763dc,13111-bldg-127,33.0,4.0,1.311103e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3399999999999999, 3.2999999999999998, 14.6...",...,53.05118,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None
2,3,b'GP\x00\x05\x0c\x1a\x00\x00\xc8K\xc3\xa5\x9av...,BLD_72de059a-ddf0-4959-be00-db8108ca4a3a,13111-bldg-429,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3300000000000001, 3.6099999999999999, 18.3...",...,64.25055,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None
3,4,b'GP\x00\x05\x0c\x1a\x00\x00\t\xc3\xd9V\x9bva@...,BLD_2297d74f-b3d5-410a-b62c-a41f6913758c,13111-bldg-406,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.4300000000000002, 3.71, 18.370000000000001...",...,39.16283,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None
4,5,b'GP\x00\x05\x0c\x1a\x00\x00\xdc\x98\xe2\xfc\x...,BLD_f6edafc1-b722-4b15-90e3-393cbb64d998,13111-bldg-511,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.77, 3.2200000000000002, 12.199999999999999...",...,48.87270,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None

In [4]:
df.isna().mean().sort_values(ascending=False)

tokyo_ward                    1.000000
name                          0.997423
規模                            0.208536
浸水ランク                         0.208536
value                         0.208536
value_uom                     0.208536
町・丁目コード                       0.123258
buildingRoofEdgeArea          0.081621
大字・町コード                       0.081621
13_区市町村コード_大字・町コード_町・丁目コード    0.081621
buildingRoofEdgeArea_uom      0.081621
surveyYear                    0.009430
districtsAndZonesType         0.000478
measuredHeight_uom            0.000120
measuredHeight                0.000120
LocalityName                  0.000000
CountryName                   0.000000
geom                          0.000000
prefecture                    0.000000
city                          0.000000
建物ID                          0.000000
key                           0.000000
codeValue                     0.000000
gml_id                        0.000000
fid                           0.000000
dtype: float64

In [5]:
df["name"].unique()

array([None, '六郷土手郵便局', '大田西六郷三郵便局', ..., '葛飾東金町五郵便局', '亀有警察署東金町交番',
       '区立半田小学校'], dtype=object)

import numpy as np

np.set_printoptions(threshold=np.inf)
df["name"].unique()

In [6]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [7]:
df.head()

,fid,geom,gml_id,建物ID,大字・町コード,町・丁目コード,13_区市町村コード_大字・町コード_町・丁目コード,規模,浸水ランク,value,value_uom,measuredHeight,measuredHeight_uom,CountryName,LocalityName,buildingRoofEdgeArea,buildingRoofEdgeArea_uom,districtsAndZonesType,prefecture,city,surveyYear,key,codeValue,name,tokyo_ward
0,1,"b'GP\x00\x05\x0c\x1a\x00\x00\x0fYDA\xcava@\xbd0<8\xcbva@i\x03\x91}Q\xc5A@\xb5\xdf\xf2dS\xc5A@sh\x91\xed|?\x03@\xd5x\xe9&1H""@\x01\xf7\x03\x00\x00\n\x00\x00\x00\x01\xeb\x03\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\xbd0<8\xcbva@\x06z!\xbfR\xc5A@sh\x91\xed|?\x03@\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@sh\x91\xed|?\x03@\x1bz\xc2\xb3\xcava@cA~6R\xc5A@sh\x91\xed|?\x03@\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@sh\x91\xed|?\x03@\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@sh\x91\xed|?\x03@\xf1\xa7j^\xcava@[j\xbf2R\xc5A@sh\x91\xed|?\x03@\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@sh\x91\xed|?\x03@\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@sh\x91\xed|?\x03@\xbd0<8\xcbva@\x06z!\xbfR\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\xbd0<8\xcbva@\x06z!\xbfR\xc5A@sh\x91\xed|?\x03@\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@sh\x91\xed|?\x03@\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@\xd5x\xe9&1H""@\xbd0<8\xcbva@\x06z!\xbfR\xc5A@\xd5x\xe9&1H""@\xbd0<8\xcbva@\x06z!\xbfR\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@sh\x91\xed|?\x03@\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@sh\x91\xed|?\x03@\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@\xd5x\xe9&1H""@\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@\xd5x\xe9&1H""@\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@sh\x91\xed|?\x03@\xf1\xa7j^\xcava@[j\xbf2R\xc5A@sh\x91\xed|?\x03@\xf1\xa7j^\xcava@[j\xbf2R\xc5A@\xd5x\xe9&1H""@\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@\xd5x\xe9&1H""@\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\xf1\xa7j^\xcava@[j\xbf2R\xc5A@sh\x91\xed|?\x03@\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@sh\x91\xed|?\x03@\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@\xd5x\xe9&1H""@\xf1\xa7j^\xcava@[j\xbf2R\xc5A@\xd5x\xe9&1H""@\xf1\xa7j^\xcava@[j\xbf2R\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@sh\x91\xed|?\x03@\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@sh\x91\xed|?\x03@\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@\xd5x\xe9&1H""@\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@\xd5x\xe9&1H""@\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@sh\x91\xed|?\x03@\x1bz\xc2\xb3\xcava@cA~6R\xc5A@sh\x91\xed|?\x03@\x1bz\xc2\xb3\xcava@cA~6R\xc5A@\xd5x\xe9&1H""@\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@\xd5x\xe9&1H""@\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x1bz\xc2\xb3\xcava@cA~6R\xc5A@sh\x91\xed|?\x03@\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@sh\x91\xed|?\x03@\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@\xd5x\xe9&1H""@\x1bz\xc2\xb3\xcava@cA~6R\xc5A@\xd5x\xe9&1H""@\x1bz\xc2\xb3\xcava@cA~6R\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@sh\x91\xed|?\x03@\xbd0<8\xcbva@\x06z!\xbfR\xc5A@sh\x91\xed|?\x03@\xbd0<8\xcbva@\x06z!\xbfR\xc5A@\xd5x\xe9&1H""@\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@\xd5x\xe9&1H""@\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@sh\x91\xed|?\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\xbd0<8\xcbva@\x06z!\xbfR\xc5A@\xd5x\xe9&1H""@\'\x08HU\xcava@\xb5\xdf\xf2dS\xc5A@\xd5x\xe9&1H""@\x0fYDA\xcava@\xa2\xe3\x0bGR\xc5A@\xd5x\xe9&1H""@\xf1\xa7j^\xcava@[j\xbf2R\xc5A@\xd5x\xe9&1H""@\xdd\xea""V\xcava@\'(8\xb8Q\xc5A@\xd5x\xe9&1H""@\xf8\xf8V\xa7\xcava@i\x03\x91}Q\xc5A@\xd5x\xe9&1H""@\x1bz\xc2\xb3\xcava@cA~6R\xc5A@\xd5x\xe9&1H""@\x1f\xc4\r)\xcbva@\xc8\x90\xc3\xe0Q\xc5A@\xd5x\xe9&1H""@\xbd0<8\xcbva@\x06z!\xbfR\xc5A@\xd5x\xe9&1H""@'",BLD_fc50c7d9-76ac-4576-bfbd-f37c74410928,13111-bldg-524,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.8400000000000001, 3.3100000000000001, 13.98, 0.17000000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",8.3,m,日本,東京都大田区東六郷三丁目,40.43768,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None
1,2,"b'GP\x00\x05\x0c\x1a\x00\x00""ht&\xa0va@\\\xc9\xea\x02\xa1va@P\xfd\xbfR,\xc5A@\xb3\xc2\xe4m/\xc5A@\xbct\x93\x18\x04V\x06@\x00\x00\x00\x00\x00@)@\x01\xf7\x03\x00\x00\x08\x00\x00\x00\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\xbct\x93\x18\x04V\x06@\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\xbct\x93\x18\x04V\x06@""ht&\xa0va@\x9dqS\x15-\xc5A@\xbct\x93\x18\x04V\x06@_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\xbct\x93\x18\x04V\x06@\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\xbct\x93\x18\x04V\x06@W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\xbct\x93\x18\x04V\x06@\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\xbct\x93\x18\x04V\x06@W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\xbct\x93\x18\x04V\x06@W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\x00\x00\x00\x00\x00@)@\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\x00\x00\x00\x00\x00@)@\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\xbct\x93\x18\x04V\x06@\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\xbct\x93\x18\x04V\x06@\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\x00\x00\x00\x00\x00@)@W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\x00\x00\x00\x00\x00@)@W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\xbct\x93\x18\x04V\x06@_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\xbct\x93\x18\x04V\x06@_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\x00\x00\x00\x00\x00@)@\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\x00\x00\x00\x00\x00@)@\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\xbct\x93\x18\x04V\x06@""ht&\xa0va@\x9dqS\x15-\xc5A@\xbct\x93\x18\x04V\x06@""ht&\xa0va@\x9dqS\x15-\xc5A@\x00\x00\x00\x00\x00@)@_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\x00\x00\x00\x00\x00@)@_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00""ht&\xa0va@\x9dqS\x15-\xc5A@\xbct\x93\x18\x04V\x06@\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\xbct\x93\x18\x04V\x06@\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\x00\x00\x00\x00\x00@)@""ht&\xa0va@\x9dqS\x15-\xc5A@\x00\x00\x00\x00\x00@)@""ht&\xa0va@\x9dqS\x15-\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\xbct\x93\x18\x04V\x06@\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\xbct\x93\x18\x04V\x06@\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\x00\x00\x00\x00\x00@)@\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\x00\x00\x00\x00\x00@)@\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\xbct\x93\x18\x04V\x06@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\x00\x00\x00\x00\x00@)@W\xaf6\xae\xa0va@\xb3\xc2\xe4m/\xc5A@\x00\x00\x00\x00\x00@)@\x1c1`\x97\xa0va@\xa6\x91\xf2\xd6.\xc5A@\x00\x00\x00\x00\x00@)@_l\xe2q\xa0va@Ze\xe7\x12/\xc5A@\x00\x00\x00\x00\x00@)@""ht&\xa0va@\x9dqS\x15-\xc5A@\x00\x00\x00\x00\x00@)@\x18J\xf4\x9f\xa0va@P\xfd\xbfR,\xc5A@\x00\x00\x00\x00\x00@)@\\\xc9\xea\x02\xa1va@\xf7\xc1\xdf\xe3.\xc5A@\x00\x00\x00\x00\x00@)@'",BLD_2e11a57e-c315-4351-8cca-22649d9763dc,13111-bldg-127,33.0,4.0,1.311103e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3399999999999999, 3.2999999999999998, 14.630000000000001, 0.26100000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",9.9,m,日本,東京都大田区仲六郷四丁目,53.05118,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None
2,3,"b'GP\x00\x05\x0c\x1a\x00\x00\xc8K\xc3\xa5\x9ava@\x9c\xbf\x9c\xaa\x9bva@\xf5e\x15\xf5H\xc5A@\xa4\x88N=L\xc5A@\x89A`\xe5\xd0""\x05@X9\xb4\xc8v~""@\x01\xf7\x03\x00\x00\x06\x00\x00\x00\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@\x89A`\xe5\xd0""\x05@G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@\x89A`\xe5\xd0""\x05@\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@\x89A`\xe5\xd0""\x05@\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@\x89A`\xe5\xd0""\x05@\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@\x89A`\xe5\xd0""\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@\x89A`\xe5\xd0""\x05@\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@\x89A`\xe5\xd0""\x05@\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@X9\xb4\xc8v~""@\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@X9\xb4\xc8v~""@\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@\x89A`\xe5\xd0""\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@\x89A`\xe5\xd0""\x05@\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@\x89A`\xe5\xd0""\x05@\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@X9\xb4\xc8v~""@\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@X9\xb4\xc8v~""@\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@\x89A`\xe5\xd0""\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@\x89A`\xe5\xd0""\x05@G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@\x89A`\xe5\xd0""\x05@G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@X9\xb4\xc8v~""@\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@X9\xb4\xc8v~""@\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@\x89A`\xe5\xd0""\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@\x89A`\xe5\xd0""\x05@\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@\x89A`\xe5\xd0""\x05@\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@X9\xb4\xc8v~""@G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@X9\xb4\xc8v~""@G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@\x89A`\xe5\xd0""\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@X9\xb4\xc8v~""@\x946\xf6\x0c\x9bva@\xa4\x88N=L\xc5A@X9\xb4\xc8v~""@\xc8K\xc3\xa5\x9ava@*q,fJ\xc5A@X9\xb4\xc8v~""@G\xd1iC\x9bva@\xf5e\x15\xf5H\xc5A@X9\xb4\xc8v~""@\x9c\xbf\x9c\xaa\x9bva@\xd4l7\xccJ\xc5A@X9\xb4\xc8v~""@'",BLD_72de059a-ddf0-4959-be00-db8108ca4a3a,13111-bldg-429,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3300000000000001, 3.6099999999999999, 18.370000000000001, 0.47899999999999998 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",7.8,m,日本,東京都大田区西六郷四丁目,64.25055,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None
3,4,b'GP\x00\x05\x0c\x1a\x00\x00\t\xc3\xd9V\x9bva@l[R\x1f\x9cva@\\V\xd9\xd7G\xc5A@\x1e*dhJ\xc5A@w\xbe\x9f\x1a/\xdd\x03@m\xe7\xfb\xa9\xf1\xd2&@\x01\xf7\x03\x00\x00\x06\x00\x00\x00\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00l[R\x1f\x9cva@#\x04\x07dI\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@w\xbe\x9f\x1a/\xdd\x03@\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@w\xbe\x9f\x1a/\xdd\x03@l[R\x1f\x9cva@#\x04\x07dI\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00l[R\x1f\x9cva@#\x04\x07dI\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@m\xe7\xfb\xa9\xf1\xd2&@l[R\x1f\x9cva@#\x04\x07dI\xc5A@m\xe7\xfb\xa9\xf1\xd2&@l[R\x1f\x9cva@#\x04\x07dI\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@w\xbe\x9f\x1a/\xdd\x03@\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@w\xbe\x9f\x1a/\xdd\x03@\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@w\xbe\x9f\x1a/\xdd\x03@l[R\x1f\x9cva@#\x04\x07dI\xc5A@w\xbe\x9f\x1a/\xdd\x03@l[R\x1f\x9cva@#\x04\x07dI\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@w\xbe\x9f\x1a/\xdd\x03@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00l[R\x1f\x9cva@#\x04\x07dI\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\x03\xac.\xa7\x9bva@\x1e*dhJ\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\t\xc3\xd9V\x9bva@3\xceX\xddH\xc5A@m\xe7\xfb\xa9\xf1\xd2&@\x1c\x8d\xfd\xce\x9bva@\\V\xd9\xd7G\xc5A@m\xe7\xfb\xa9\xf1\xd2&@l[R\x1f\x9cva@#\x04\x07dI\xc5A@m\xe7\xfb\xa9\xf1\xd2&@',BLD_2297d74f-b3d5-410a-b62c-a41f6913758c,13111-bldg-406,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.4300000000000002, 3.71, 18.370000000000001, 0.47899999999999998 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",9.5,m,日本,東京都大田区西六郷四丁目,39.16283,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None
4,5,"b'GP\x00\x05\x0c\x1a\x00\x00\xdc\x98\xe2\xfc\xbbva@\x88""k+\xbdva@K\xd8\x937P\xc5A@\x0e@\x83\x85R\xc5A@\xd1""\xdb\xf9~j\x05@\x85\xebQ\xb8\x1e\x85!@\x01\xf7\x03\x00\x00\x07\x00\x00\x00\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\xd1""\xdb\xf9~j\x05@\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\xd1""\xdb\xf9~j\x05@MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\xd1""\xdb\xf9~j\x05@\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\xd1""\xdb\xf9~j\x05@\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\xd1""\xdb\xf9~j\x05@D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\xd1""\xdb\xf9~j\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\xd1""\xdb\xf9~j\x05@\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\xd1""\xdb\xf9~j\x05@\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\x85\xebQ\xb8\x1e\x85!@D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\x85\xebQ\xb8\x1e\x85!@D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\xd1""\xdb\xf9~j\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\xd1""\xdb\xf9~j\x05@\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\xd1""\xdb\xf9~j\x05@\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\x85\xebQ\xb8\x1e\x85!@\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\x85\xebQ\xb8\x1e\x85!@\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\xd1""\xdb\xf9~j\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\xd1""\xdb\xf9~j\x05@MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\xd1""\xdb\xf9~j\x05@MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\x85\xebQ\xb8\x1e\x85!@\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\x85\xebQ\xb8\x1e\x85!@\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\xd1""\xdb\xf9~j\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\xd1""\xdb\xf9~j\x05@\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\xd1""\xdb\xf9~j\x05@\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\x85\xebQ\xb8\x1e\x85!@MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\x85\xebQ\xb8\x1e\x85!@MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\xd1""\xdb\xf9~j\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\xd1""\xdb\xf9~j\x05@D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\xd1""\xdb\xf9~j\x05@D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\x85\xebQ\xb8\x1e\x85!@\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\x85\xebQ\xb8\x1e\x85!@\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\xd1""\xdb\xf9~j\x05@\x01\xeb\x03\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\x85\xebQ\xb8\x1e\x85!@\x95\x1b\x9d\x1a\xbcva@\x0e@\x83\x85R\xc5A@\x85\xebQ\xb8\x1e\x85!@\xdc\x98\xe2\xfc\xbbva@?E\x1blQ\xc5A@\x85\xebQ\xb8\x1e\x85!@MD\xb0\r\xbdva@K\xd8\x937P\xc5A@\x85\xebQ\xb8\x1e\x85!@\x88""k+\xbdva@\xb8\xb7\x94MQ\xc5A@\x85\xebQ\xb8\x1e\x85!@D\xbcI\x17\xbdva@*\xe9.dQ\xc5A@\x85\xebQ\xb8\x1e\x85!@'",BLD_f6edafc1-b722-4b15-90e3-393cbb64d998,13111-bldg-511,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.77, 3.2200000000000002, 12.199999999999999, 0.029000000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",6.5,m,日本,東京都大田区東六郷三丁目,48.87270,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None

In [8]:
df = df.drop(columns=["geom"])

In [9]:
df.head()

,fid,gml_id,建物ID,大字・町コード,町・丁目コード,13_区市町村コード_大字・町コード_町・丁目コード,規模,浸水ランク,value,value_uom,measuredHeight,measuredHeight_uom,CountryName,LocalityName,buildingRoofEdgeArea,buildingRoofEdgeArea_uom,districtsAndZonesType,prefecture,city,surveyYear,key,codeValue,name,tokyo_ward
0,1,BLD_fc50c7d9-76ac-4576-bfbd-f37c74410928,13111-bldg-524,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.8400000000000001, 3.3100000000000001, 13.98, 0.17000000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",8.3,m,日本,東京都大田区東六郷三丁目,40.43768,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None
1,2,BLD_2e11a57e-c315-4351-8cca-22649d9763dc,13111-bldg-127,33.0,4.0,1.311103e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3399999999999999, 3.2999999999999998, 14.630000000000001, 0.26100000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",9.9,m,日本,東京都大田区仲六郷四丁目,53.05118,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None
2,3,BLD_72de059a-ddf0-4959-be00-db8108ca4a3a,13111-bldg-429,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3300000000000001, 3.6099999999999999, 18.370000000000001, 0.47899999999999998 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",7.8,m,日本,東京都大田区西六郷四丁目,64.25055,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None
3,4,BLD_2297d74f-b3d5-410a-b62c-a41f6913758c,13111-bldg-406,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.4300000000000002, 3.71, 18.370000000000001, 0.47899999999999998 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",9.5,m,日本,東京都大田区西六郷四丁目,39.16283,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None
4,5,BLD_f6edafc1-b722-4b15-90e3-393cbb64d998,13111-bldg-511,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.77, 3.2200000000000002, 12.199999999999999, 0.029000000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",6.5,m,日本,東京都大田区東六郷三丁目,48.87270,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None

In [10]:
import numpy as np
import pandas as pd
import ast
import numbers

def max_flood_depth(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return np.nan

    # If it's a string like "[1.84, 3.31, 13.98, 0.17]"
    if isinstance(v, str):
        try:
            v = ast.literal_eval(v)
        except Exception:
            return np.nan

    nums = []

    def walk(x):
        # numpy arrays, lists, tuples
        if isinstance(x, (list, tuple, np.ndarray)):
            for t in x:
                walk(t)
        # any numeric type (python, numpy, decimal, etc.)
        elif isinstance(x, numbers.Number) and not pd.isna(x):
            nums.append(float(x))

    walk(v)
    return max(nums) if nums else np.nan

df["max_flood_depth"] = df["value"].apply(max_flood_depth)

In [11]:
df.head()

,fid,gml_id,建物ID,大字・町コード,町・丁目コード,13_区市町村コード_大字・町コード_町・丁目コード,規模,浸水ランク,value,value_uom,measuredHeight,measuredHeight_uom,CountryName,LocalityName,buildingRoofEdgeArea,buildingRoofEdgeArea_uom,districtsAndZonesType,prefecture,city,surveyYear,key,codeValue,name,tokyo_ward,max_flood_depth
0,1,BLD_fc50c7d9-76ac-4576-bfbd-f37c74410928,13111-bldg-524,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.8400000000000001, 3.3100000000000001, 13.98, 0.17000000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",8.3,m,日本,東京都大田区東六郷三丁目,40.43768,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None,13.98
1,2,BLD_2e11a57e-c315-4351-8cca-22649d9763dc,13111-bldg-127,33.0,4.0,1.311103e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3399999999999999, 3.2999999999999998, 14.630000000000001, 0.26100000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",9.9,m,日本,東京都大田区仲六郷四丁目,53.05118,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None,14.63
2,3,BLD_72de059a-ddf0-4959-be00-db8108ca4a3a,13111-bldg-429,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.3300000000000001, 3.6099999999999999, 18.370000000000001, 0.47899999999999998 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",7.8,m,日本,東京都大田区西六郷四丁目,64.25055,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None,18.37
3,4,BLD_2297d74f-b3d5-410a-b62c-a41f6913758c,13111-bldg-406,38.0,4.0,1.311104e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 2.4300000000000002, 3.71, 18.370000000000001, 0.47899999999999998 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",9.5,m,日本,東京都大田区西六郷四丁目,39.16283,m2,12.0,13,13111,2016.0,"[ 2, 106 ]","[ 2, 20 ]",None,None,18.37
4,5,BLD_f6edafc1-b722-4b15-90e3-393cbb64d998,13111-bldg-511,49.0,3.0,1.311105e+10,"[ ""L1"", ""L2"", ""L2"" ]","[ 2, 3, 1 ]","[ 1.77, 3.2200000000000002, 12.199999999999999, 0.029000000000000001 ]","[ ""m"", ""m"", ""hour"", ""m"" ]",6.5,m,日本,東京都大田区東六郷三丁目,48.87270,m2,11.0,13,13111,2016.0,"[ 2, 105, 106 ]","[ 2, 2, 20 ]",None,None,12.20

In [12]:
df["max_flood_depth"].isna().sum()

np.int64(570556)

In [13]:
df["value"].isna().sum()

np.int64(570556)

In [14]:
drop_cols = [
    "fid",
    "gml_id",
    "建物ID",
    "13_区市町村コード_大字・町コード_町・丁目コード",
    "codeValue",
    "key",
    "districtsAndZonesType",
    "value",
    "value_uom",
    "浸水ランク",
    "measuredHeight_uom",
    "buildingRoofEdgeArea_uom",
    "prefecture",
]

df = df.drop(columns=drop_cols)

In [15]:
df.head()

,大字・町コード,町・丁目コード,規模,measuredHeight,CountryName,LocalityName,buildingRoofEdgeArea,city,surveyYear,name,tokyo_ward,max_flood_depth
0,49.0,3.0,"[ ""L1"", ""L2"", ""L2"" ]",8.3,日本,東京都大田区東六郷三丁目,40.43768,13111,2016.0,None,None,13.98
1,33.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",9.9,日本,東京都大田区仲六郷四丁目,53.05118,13111,2016.0,None,None,14.63
2,38.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",7.8,日本,東京都大田区西六郷四丁目,64.25055,13111,2016.0,None,None,18.37
3,38.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",9.5,日本,東京都大田区西六郷四丁目,39.16283,13111,2016.0,None,None,18.37
4,49.0,3.0,"[ ""L1"", ""L2"", ""L2"" ]",6.5,日本,東京都大田区東六郷三丁目,48.87270,13111,2016.0,None,None,12.20

In [16]:
jp_to_en = {
    "千代田区": "Chiyoda",
    "中央区": "Chuo",
    "港区": "Minato",
    "新宿区": "Shinjuku",
    "文京区": "Bunkyo",
    "台東区": "Taito",
    "墨田区": "Sumida",
    "江東区": "Koto",
    "品川区": "Shinagawa",
    "目黒区": "Meguro",
    "大田区": "Ota",
    "世田谷区": "Setagaya",
    "渋谷区": "Shibuya",
    "中野区": "Nakano",
    "杉並区": "Suginami",
    "豊島区": "Toshima",
    "北区": "Kita",
    "荒川区": "Arakawa",
    "板橋区": "Itabashi",
    "練馬区": "Nerima",
    "足立区": "Adachi",
    "葛飾区": "Katsushika",
    "江戸川区": "Edogawa",
}

pattern = "|".join(jp_to_en.keys())

df["tokyo_ward"] = (df["LocalityName"].str.extract(f"({pattern})", expand=False).map(jp_to_en))

In [17]:
df.head()

,大字・町コード,町・丁目コード,規模,measuredHeight,CountryName,LocalityName,buildingRoofEdgeArea,city,surveyYear,name,tokyo_ward,max_flood_depth
0,49.0,3.0,"[ ""L1"", ""L2"", ""L2"" ]",8.3,日本,東京都大田区東六郷三丁目,40.43768,13111,2016.0,None,Ota,13.98
1,33.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",9.9,日本,東京都大田区仲六郷四丁目,53.05118,13111,2016.0,None,Ota,14.63
2,38.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",7.8,日本,東京都大田区西六郷四丁目,64.25055,13111,2016.0,None,Ota,18.37
3,38.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",9.5,日本,東京都大田区西六郷四丁目,39.16283,13111,2016.0,None,Ota,18.37
4,49.0,3.0,"[ ""L1"", ""L2"", ""L2"" ]",6.5,日本,東京都大田区東六郷三丁目,48.87270,13111,2016.0,None,Ota,12.20

In [18]:
df["tokyo_ward"].value_counts()

tokyo_ward
Setagaya      357942
Ota           292138
Suginami      248488
Nerima        241001
Adachi        156832
Edogawa       145592
Nakano        135212
Shinagawa     127698
Itabashi      113476
Toshima       107129
Katsushika    106848
Meguro        106602
Shinjuku      104152
Kita           78857
Shibuya        77072
Koto           62931
Minato         56476
Bunkyo         55105
Sumida         46386
Arakawa        41186
Taito          38156
Chuo           22457
Chiyoda        14271
Name: count, dtype: int64

In [19]:
df.isna().mean().sort_values(ascending=False)

name                    0.997423
規模                      0.208536
max_flood_depth         0.208536
町・丁目コード                 0.123258
大字・町コード                 0.081621
buildingRoofEdgeArea    0.081621
surveyYear              0.009430
measuredHeight          0.000120
CountryName             0.000000
LocalityName            0.000000
city                    0.000000
tokyo_ward              0.000000
dtype: float64

In [20]:
import re

rename_map = {
    "町・丁目コード": "chome_code",
    "大字・町コード": "town_code",
    "規模": "flood_scale",

    "LocalityName": "locality_name",
    "CountryName": "country_name",
    "measuredHeight": "measured_height",
    "buildingRoofEdgeArea": "building_roof_edge_area",

    "max_flood_depth": "max_flood_depth",  # keep
    "tokyo_ward": "tokyo_ward",
    "surveyYear": "survey_year",
}

df = df.rename(columns=rename_map)

In [21]:
df.head()

,town_code,chome_code,flood_scale,measured_height,country_name,locality_name,building_roof_edge_area,city,survey_year,name,tokyo_ward,max_flood_depth
0,49.0,3.0,"[ ""L1"", ""L2"", ""L2"" ]",8.3,日本,東京都大田区東六郷三丁目,40.43768,13111,2016.0,None,Ota,13.98
1,33.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",9.9,日本,東京都大田区仲六郷四丁目,53.05118,13111,2016.0,None,Ota,14.63
2,38.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",7.8,日本,東京都大田区西六郷四丁目,64.25055,13111,2016.0,None,Ota,18.37
3,38.0,4.0,"[ ""L1"", ""L2"", ""L2"" ]",9.5,日本,東京都大田区西六郷四丁目,39.16283,13111,2016.0,None,Ota,18.37
4,49.0,3.0,"[ ""L1"", ""L2"", ""L2"" ]",6.5,日本,東京都大田区東六郷三丁目,48.87270,13111,2016.0,None,Ota,12.20

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2736007 entries, 0 to 2736006
Data columns (total 12 columns):
 #   Column                   Dtype
---  ------                   -----
 0   town_code                float64
 1   chome_code               float64
 2   flood_scale              object
 3   measured_height          float64
 4   country_name             object
 5   locality_name            object
 6   building_roof_edge_area  float64
 7   city                     int64
 8   survey_year              float64
 9   name                     object
 10  tokyo_ward               object
 11  max_flood_depth          float64
dtypes: float64(6), int64(1), object(5)
memory usage: 250.5+ MB

In [24]:
df.to_csv("buildings_tokyo.csv", index=False, encoding="utf-8-sig")